### PR TITLE
Added placeholder for items uploaded without image

### PR DESCRIPTION
**Pull request by W5DEV**
# Description

Added logic to add a placeholder if no image is present on a given item. 
Screen Shot 2022-10-30 at 4 01 52 AM

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Thanks JLarsonMWI, I'll review the changes right away!

**Review by vanessa-cooper — DISMISSED** [review]
Make sure all checks pass, only then you can merge the PR.

**Comment by W5DEV** [comment]
> Make sure all checks pass, only then you can merge the PR.

This has been resolved.

**Comment by vanessa-cooper** [comment]
Thanks JLarsonMWI, I'll review the changes right away!

**Pull request closed without merging**
